version: '3.9'

services:
  mongo:
    image: mongo:5.0.5
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network

  backend:
    build: ./backend
    restart: always
    environment:
      MONGO_USERNAME: root
      MONGO_PASSWORD: root
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      NODE_ENV: production
    ports:
      - '3051:3051'
    depends_on:
      - mongo
    networks:
      - app_network

  frontend:
    build: ./frontend
    restart: always
    environment:
      API_URL: http://backend:3051
    ports:
      - '3001:3001'
    networks:
      - app_network

networks:
  app_network:

volumes:
  mongo_data:
