POST http://localhost:3051/auth/register
Content-Type: application/json

{
  "username": "correia",
  "password": "testtest"
}

###

POST http://localhost:3000/item/
Content-Type: application/json

{
  "_id" : "2",
  "name" : "star wars",
  "type" : "jogo",
  "description" : "um bom jogo",
  "platform": "steam",
  "language":"portugues",
  "price":"100",
  "general_classification":"5",
  "evaluations":"very good"
}

### login

POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "correia",
  "password": "testtest"
}